// This file is generated by the schema import script.

import accounts from './accounts.json';
import addressBooks from './addressBook.json';
import alarms from './alarms.json';
import browserAction from './browserAction.json';
import browserSettings from './browser_settings.json';
import clipboard from './clipboard.json';
import cloudFile from './cloudFile.json';
import commands from './commands.json';
import compose from './compose.json';
import composeAction from './composeAction.json';
import contacts from './contacts.json';
import contentScripts from './content_scripts.json';
import contextualIdentities from './contextual_identities.json';
import cookies from './cookies.json';
import dns from './dns.json';
import downloads from './downloads.json';
import events from './events.json';
import experiments from './experiments.json';
import extension from './extension.json';
import extension_protocol_handlers from './extension_protocol_handlers.json';
import extensionTypes from './extension_types.json';
import i18n from './i18n.json';
import identity from './identity.json';
import idle from './idle.json';
import legacy from './legacy.json';
import mailingLists from './mailingLists.json';
import mailTabs from './mailTabs.json';
import management from './management.json';
import menus from './menus.json';
import messages from './messages.json';
import native_manifest from './native_manifest.json';
import notifications from './notifications.json';
import permissions from './permissions.json';
import pkcs11 from './pkcs11.json';
import privacy from './privacy.json';
import proxy from './proxy.json';
import runtime from './runtime.json';
import storage from './storage.json';
import tabs from './tabs.json';
import telemetry from './telemetry.json';
import test from './test.json';
import theme from './theme.json';
import topSites from './top_sites.json';
import types from './types.json';
import userScripts from './userScripts.json';
import webNavigation from './web_navigation.json';
import webRequest from './web_request.json';
import windows from './windows.json';
import contextMenus from './context_menus.json';
export default [
  accounts,
  addressBooks,
  alarms,
  browserAction,
  browserSettings,
  clipboard,
  cloudFile,
  commands,
  compose,
  composeAction,
  contacts,
  contentScripts,
  contextualIdentities,
  cookies,
  dns,
  downloads,
  events,
  experiments,
  extension,
  extension_protocol_handlers,
  extensionTypes,
  i18n,
  identity,
  idle,
  legacy,
  mailingLists,
  mailTabs,
  management,
  menus,
  messages,
  native_manifest,
  notifications,
  permissions,
  pkcs11,
  privacy,
  proxy,
  runtime,
  storage,
  tabs,
  telemetry,
  test,
  theme,
  topSites,
  types,
  userScripts,
  webNavigation,
  webRequest,
  windows,
  contextMenus,
];
